#!/bin/bash
#PBS -q condo
#PBS -N Na3AlH6_Relax
#PBS -l nodes=1:ppn=1
#PBS -l walltime=08:00:00
#PBS -o $PBS_JOBID.log
#PBS -e err
#PBS -M jpusteln@ucsd.edu
#PBS -V
#PBS -A ong-group
nohup python3 -u Research_Lab/Na3AlH6/time/m3gnet_relax.py >> Research_Lab/Na3AlH6/time/Final_E 2>&1