#!/bin/bash
#PBS -q condo
#PBS -N NaZr2(PO4)3_Energy
#PBS -l nodes=1:ppn=1
#PBS -l walltime=08:00:00
#PBS -o $PBS_JOBID.log
#PBS -e err
#PBS -M jpusteln@ucsd.edu
#PBS -V
#PBS -A ong-group
nohup python3 -u Research_Lab/NaZr2P3O12/MD_sim_300.py >> Research_Lab/NaZr2P3O12/output300 2>&1