#!/bin/bash
#PBS -q condo
#PBS -N NaBH4_Time
#PBS -l nodes=1:ppn=1
#PBS -l walltime=08:00:00
#PBS -o $PBS_JOBID.log
#PBS -e err
#PBS -M jpusteln@ucsd.edu
#PBS -V
#PBS -A ong-group
nohup python3 -u Research_Lab/NaBH4/time/time_111.py >> Research_Lab/NaBH4/time/output111 2>&1