#!/bin/bash
#PBS -q home-ong
#PBS -N Na3Zr2Si2PO12_Energy
#PBS -l nodes=1:ppn=1
#PBS -l walltime=26:00:00
#PBS -o $PBS_JOBID.log
#PBS -e err
#PBS -M jpusteln@ucsd.edu
#PBS -V
#PBS -A ong-group
nohup python3 -u Research_Lab/Na3Zr2Si2PO12/MD_sim_700.py >> Research_Lab/Na3Zr2Si2PO12/output700 2>&1