#!/bin/bash
#PBS -q home-ong
#PBS -N NaBH4_Energy
#PBS -l nodes=1:ppn=1
#PBS -l walltime=36:00:00
#PBS -o $PBS_JOBID.log
#PBS -e err
#PBS -M jpusteln@ucsd.edu
#PBS -V
#PBS -A ong-group
nohup python3 -u Research_Lab/NaBH4/MD_sim_300.py >> Research_Lab/NaBH4/output300 2>&1